### ISSUE TITLE
[PATCH v2 0/4] Introduce a mmap sem to deal with some mmap issues

### ISSUE THREAD

**Issue by josefbacik** [btrfs/linux#163]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1607969636.git.josef@toxicpanda.com/

b4 am cover.1607969636.git.josef@toxicpanda.com

**Comment by fdmanana** [comment]
I've been having delays with posts to vger lists, so I haven't received the mail for this patchset yet (haven been with 2 to 3 delays since last week, happens from time to time), and some messages seem to be lost by now.

The patchset replaces the following patches:

https://patchwork.kernel.org/project/linux-btrfs/list/?series=401397
https://patchwork.kernel.org/project/linux-btrfs/list/?series=400859

It isn't mentioned in the cover letter, so it might not be obvious for everyone, since the discussion that lead to it was on Slack.

The whole patchset looks good to me, and seems to work just fine as expected.

Reviewed-by: Filipe Manana <fdmanana@suse.com>

**Comment by josefbacik** [comment]
Link to patches

https://lore.kernel.org/linux-btrfs/cover.1612995212.git.josef@toxicpanda.com/

b4 am cover.1612995212.git.josef@toxicpanda.com
